import {
  convertMovieToHls,
  createMovieHlsFormat,
  createMpegTsHlsFormat,
  decodeMovieHlsText,
  type MovieHlsAsset,
  type MovieHlsOptions,
  type MovieHlsSegmentFormatOptions,
  type MovieHlsVariantOptions,
} from './hls.js';
import {
  buildMovieAudioConversionOptions,
  buildMovieConversionOptions,
  buildMovieVideoConversionOptions,
  checkMovieAudioEncoderConfigSupport,
  checkMovieAudioEncoderSupport,
  checkMovieConversionSupport,
  checkMovieRawFrameSupport,
  checkMovieVideoEncoderBitDepthSupport,
  checkMovieVideoEncoderConfigSupport,
  inspectMovie,
  inspectVideoTrackColor,
  type BrowserMovieAudioConversionOptionsInput,
  type BrowserMovieAudioConversionPlan,
  type BrowserMovieAudioEncoderConfigSupportOptions,
  type BrowserMovieAudioEncoderConfigSupportResult,
  type BrowserMovieAudioEncoderSupportOptions,
  type BrowserMovieAudioEncoderSupportResult,
  type BrowserMovieAudioOptions,
  type BrowserMovieColorMetadataPolicy,
  type BrowserMovieConversionOptionsInput,
  type BrowserMovieConversionPlan,
  type BrowserMovieConversionSupportResult,
  type BrowserMovieConversionWarning,
  type BrowserMovieDiscardedTrackResult,
  type BrowserMovieQuantizerOptions,
  type BrowserMovieRawBitDepth,
  type BrowserMovieRawChromaSubsampling,
  type BrowserMovieRawFrameSupportOptions,
  type BrowserMovieRawFrameSupportResult,
  type BrowserMovieResizeFit,
  type BrowserMovieResizeOptions,
  type BrowserMovieResizePath,
  type BrowserMovieTrackColor,
  type BrowserMovieTrackSupportResult,
  type BrowserMovieVideoConversionOptionsInput,
  type BrowserMovieVideoConversionPlan,
  type BrowserMovieVideoEncoderBitDepthSupportOptions,
  type BrowserMovieVideoEncoderBitDepthSupportResult,
  type BrowserMovieVideoEncoderConfigSupportResult,
  type BrowserMovieVideoOptions,
  type SceneDetectionOptions,
  type SceneKeyFrameState,
} from './conversion-options.js';

export type {
  BrowserMovieAudioConversionOptionsInput,
  BrowserMovieAudioConversionPlan,
  BrowserMovieAudioEncoderConfigSupportOptions,
  BrowserMovieAudioEncoderConfigSupportResult,
  BrowserMovieAudioEncoderSupportOptions,
  BrowserMovieAudioEncoderSupportResult,
  BrowserMovieAudioOptions,
  BrowserMovieColorMetadataPolicy,
  BrowserMovieConversionOptionsInput,
  BrowserMovieConversionPlan,
  BrowserMovieConversionSupportResult,
  BrowserMovieConversionWarning,
  BrowserMovieDiscardedTrackResult,
  BrowserMovieQuantizerOptions,
  BrowserMovieRawBitDepth,
  BrowserMovieRawChromaSubsampling,
  BrowserMovieRawFrameSupportOptions,
  BrowserMovieRawFrameSupportResult,
  BrowserMovieResizeFit,
  BrowserMovieResizeOptions,
  BrowserMovieResizePath,
  BrowserMovieTrackColor,
  BrowserMovieTrackSupportResult,
  BrowserMovieVideoConversionOptionsInput,
  BrowserMovieVideoConversionPlan,
  BrowserMovieVideoEncoderBitDepthSupportOptions,
  BrowserMovieVideoEncoderBitDepthSupportResult,
  BrowserMovieVideoEncoderConfigSupportResult,
  BrowserMovieVideoOptions,
  MovieHlsAsset,
  MovieHlsOptions,
  MovieHlsSegmentFormatOptions,
  MovieHlsVariantOptions,
  SceneDetectionOptions,
  SceneKeyFrameState,
};

export {
  buildMovieAudioConversionOptions,
  buildMovieConversionOptions,
  buildMovieVideoConversionOptions,
  checkMovieAudioEncoderConfigSupport,
  checkMovieAudioEncoderSupport,
  checkMovieConversionSupport,
  checkMovieRawFrameSupport,
  checkMovieVideoEncoderBitDepthSupport,
  checkMovieVideoEncoderConfigSupport,
  convertMovieToHls,
  createMovieHlsFormat,
  createMpegTsHlsFormat,
  decodeMovieHlsText,
  inspectMovie,
  inspectVideoTrackColor,
};
